'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System.Runtime.Serialization

Namespace CustomService
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="ServiceException", [Namespace]:="http://schemas.datacontract.org/2004/07/CustomService")>  _
    Partial Public Class ServiceException
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject
        
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        Private InnerExceptionMessageField As String
        
        Private MessageField As String
        
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property InnerExceptionMessage() As String
            Get
                Return Me.InnerExceptionMessageField
            End Get
            Set
                Me.InnerExceptionMessageField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Message() As String
            Get
                Return Me.MessageField
            End Get
            Set
                Me.MessageField = value
            End Set
        End Property
    End Class
End Namespace


<System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
 System.ServiceModel.ServiceContractAttribute([Namespace]:="http://verizon.com/adcomparator", ConfigurationName:="IAdComparator")>  _
Public Interface IAdComparator
    
    <System.ServiceModel.OperationContractAttribute(Action:="http://verizon.com/adcomparator/IAdComparator/SetStart", ReplyAction:="http://verizon.com/adcomparator/IAdComparator/SetStartResponse"),  _
     System.ServiceModel.FaultContractAttribute(GetType(CustomService.ServiceException), Action:="http://verizon.com/adcomparator/IAdComparator/SetStartServiceExceptionFault", Name:="ServiceException", [Namespace]:="http://schemas.datacontract.org/2004/07/CustomService")>  _
    Sub SetStart(ByVal Number As Integer)
    
    <System.ServiceModel.OperationContractAttribute(Action:="http://verizon.com/adcomparator/IAdComparator/SetStop", ReplyAction:="http://verizon.com/adcomparator/IAdComparator/SetStopResponse"),  _
     System.ServiceModel.FaultContractAttribute(GetType(CustomService.ServiceException), Action:="http://verizon.com/adcomparator/IAdComparator/SetStopServiceExceptionFault", Name:="ServiceException", [Namespace]:="http://schemas.datacontract.org/2004/07/CustomService")>  _
    Sub SetStop(ByVal Number As Integer)
    
    <System.ServiceModel.OperationContractAttribute(Action:="http://verizon.com/adcomparator/IAdComparator/GetCount", ReplyAction:="http://verizon.com/adcomparator/IAdComparator/GetCountResponse"),  _
     System.ServiceModel.FaultContractAttribute(GetType(CustomService.ServiceException), Action:="http://verizon.com/adcomparator/IAdComparator/GetCountServiceExceptionFault", Name:="ServiceException", [Namespace]:="http://schemas.datacontract.org/2004/07/CustomService")>  _
    Function GetCount() As Integer
    
    <System.ServiceModel.OperationContractAttribute(Action:="http://verizon.com/adcomparator/IAdComparator/GetStatus", ReplyAction:="http://verizon.com/adcomparator/IAdComparator/GetStatusResponse"),  _
     System.ServiceModel.FaultContractAttribute(GetType(CustomService.ServiceException), Action:="http://verizon.com/adcomparator/IAdComparator/GetStatusServiceExceptionFault", Name:="ServiceException", [Namespace]:="http://schemas.datacontract.org/2004/07/CustomService")>  _
    Function GetStatus() As String
End Interface

<System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
Public Interface IAdComparatorChannel
    Inherits IAdComparator, System.ServiceModel.IClientChannel
End Interface

<System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
Partial Public Class AdComparatorClient
    Inherits System.ServiceModel.ClientBase(Of IAdComparator)
    Implements IAdComparator
    
    Public Sub New()
        MyBase.New
    End Sub
    
    Public Sub New(ByVal endpointConfigurationName As String)
        MyBase.New(endpointConfigurationName)
    End Sub
    
    Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
        MyBase.New(endpointConfigurationName, remoteAddress)
    End Sub
    
    Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
        MyBase.New(endpointConfigurationName, remoteAddress)
    End Sub
    
    Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
        MyBase.New(binding, remoteAddress)
    End Sub
    
    Public Sub SetStart(ByVal Number As Integer) Implements IAdComparator.SetStart
        MyBase.Channel.SetStart(Number)
    End Sub
    
    Public Sub SetStop(ByVal Number As Integer) Implements IAdComparator.SetStop
        MyBase.Channel.SetStop(Number)
    End Sub
    
    Public Function GetCount() As Integer Implements IAdComparator.GetCount
        Return MyBase.Channel.GetCount
    End Function
    
    Public Function GetStatus() As String Implements IAdComparator.GetStatus
        Return MyBase.Channel.GetStatus
    End Function
End Class
